#!/bin/bash

# copy custom configuration
cp linux/conf/.bashrc ~/
cp linux/conf/.gitconfig ~/
cp linux/conf/.vimrc ~/

# create workspace
mkdir -p ~/workspace
sudo ln -s ~/workspace /workspace

# install favorite applications
sudo apt-get install vim
sudo apt-get install gthumb
sudo apt-get install eclipse
sudo apt-get install ssh
sudo apt-get install git
sudo apt-get install gitk

# install webkit related packages
